spring.application.name=AuthenticationService

jwt.secret=bXlzdXBlcnNlY3JldGtleWZvcnRlc3RpbmcyMzQyMzRrbmpzbGRmampzZGxrbmpzZGY
jwt.expiration.access=900000
jwt.expiration.refresh=604800000

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_bd
spring.datasource.username=admin
spring.datasource.password=3121
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

server.port=8081
logging.level.org.springframework.security=DEBUG
