version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: order_postgres_db
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 3121
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  order-service:
    build: .
    container_name: order_service_app
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/order_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=3121
      - CLIENT_USER_SERVICE_URL=http://host.docker.internal:8080
    depends_on:
      - postgres-db

volumes:
  postgres_data: