spring.application.name=OrderService
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=admin
spring.datasource.password=3121
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
server.port=8082
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
client.user-service.url=http://localhost:8080
resilience4j.circuitbreaker.instances.user-service-cb.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.user-service-cb.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.user-service-cb.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.user-service-cb.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.user-service-cb.sliding-window-size=10
resilience4j.circuitbreaker.instances.user-service-cb.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.user-service-cb.register-health-indicator=true