spring:
  application:
    name: project

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false

server:
  port: 8080